services:
  - type: web
    name: chat-bloom-93-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        value: mongodb+srv://abhishek:abhi12345@chatbloom.y25xzwt.mongodb.net/chat-bloom-93
      - key: FRONTEND_URL
        value: https://chatbloombyabhishek.netlify.app
      - key: JWT_SECRET
        generateValue: true
